import pandas as pd
import os

data = {
    "SummaryRequest" : ["Could you please summarize this email thread for me?",
                        "I need a quick summary of the attached document.",                       
                        "Please give me a short summary of the meeting notes.",
                        "Can you summarize what was discussed in the last call?",
                        "Provide a summary of the report attached.",
                        "I don’t have time to read this, can you just summarize it?",
                        "Summarize the key points from this article.",
                        "Can I get a summary of yesterday’s presentation?",
                        "Summarize this PDF into bullet points.",
                        "Please extract and summarize the main ideas from this email.",
                        "Give me a one-liner summary of this message.",
                        "What are the takeaways from this thread?",
                        "Can you give a TL;DR of the email chain?",
                        "I just received a long email, can you break it down?",
                        "Quick summary of this Slack conversation, please.",
                        "What's the gist of this report?",
                        "Boil down this document into a few lines.",
                        "Need a summary of this discussion.",
                        "Give me a high-level overview of this.",
                        "Please condense the content of this email.",
                        "Could you draft a short summary of this message?",
                        "Create a brief summary from this article.",
                        "Summarize the conversation we had over email.",
                        "I need the main highlights from this report.",
                        "What are the key points from this communication?",
                        "Can you reduce this to a short version?",
                        "Provide a summarized version of this long email.",
                        "Help me understand this in a few bullet points.",
                        "Give me a short breakdown of this information.",
                        "Please highlight the most important parts of this.",
                        "I want a summarized briefing of this note.",
                        "Give a concise recap of this conversation.",
                        "I don’t need the details, just the summary please.",
                        "Can you help by giving a short version of this email?",
                        "Extract key insights from this attachment.",
                        "Break down this document for me.",
                        "Give me the core message from this thread.",
                        "Summarize the following forwarded message.",
                        "I'd like a quick digest of this content.",
                        "Make a summary of this newsletter.",
                        "Can you provide a short recap of this event?",
                        "Help me get the crux of this lengthy email.",
                        "Bullet point summary of this article, please.",
                        "Write a summary paragraph for this.",
                        "Can you summarize the feedback from this email chain?",
                        "I need a quick look at the contents here.",
                        "What are the essential parts of this message?",
                        "Give me a TL;DR of this attachment.",
                        "Send me a summarized version of this memo.",
                        "Review and summarize this long communication.",
                        "Could you quickly summarize the key points from this message?",
                        "I don’t have time to read the full email, can you give me a summary?",
                        "Summarize the content of this email for me.",
                        "Give me a TL;DR of this message.",
                        "What’s the main idea of this email?",
                        "Can you condense this email into a few lines?",
                        "I just want a brief of what this email says.",
                        "Highlight only the important parts of this mail.",
                        "Provide a short summary of the message below.",
                        "Summarize the email in two sentences.",
                        "I need a quick overview of this conversation.",
                        "Extract the main points from this email.",
                        "What is this person trying to say in short?",
                        "Give me the gist of this email.",
                        "Can you tell me the takeaway from this email?",
                        "Help me understand this email faster – summarize it.",
                        "Generate a summary of this email’s contents.",
                        "Provide a brief explanation of what this email is about.",
                        "Just tell me what this email is about.",
                        "What's the summary of this email chain?",
                        "Can I get a summary of the email thread?",
                        "Give me the main highlights of this message.",
                        "Provide me with a concise version of this email.",
                        "Extract the core message from this email.",
                        "Summarize this long message into a short paragraph.",
                        "Could you summarize this for a meeting update?",
                        "I need a summarized version to forward to my team.",
                        "This email is too long; what’s the short version?",
                        "Quick summary please — what’s this about?",
                        "Boil down this email to its essentials.",
                        "What’s the most important point here?",
                        "Just a summary of the action items would be great.",
                        "Turn this email into a bullet-point summary.",
                        "Can you paraphrase this into a short brief?",
                        "Draft a quick summary I can send to my manager.",
                        "Make this email easier to understand.",
                        "Help me summarize this for a report.",
                        "I need a summary of the attached email.",
                        "Rephrase this email into a short recap.",
                        "What’s the email saying in simple terms?",
                        "Please write a one-line summary of this.",
                        "Extract the subject and summarize the body.",
                        "Too much text, summarize it please.",
                        "Make this email more digestible — summary only.",
                        "Skip the fluff — what’s the email about?",
                        "Can I have a short, sharp summary?",
                        "Condense this into 3 bullet points.",
                        "I’m too busy to read it, summarize?",
                        "Give me just the core message.",
                        "Quickly tell me what this email is trying to say.",
                        "What is the crux of this email?"],

    "InfoRequest" :    ["Can you tell me more about the pricing?",
                        "I need details on the onboarding process.",
                        "Could you share the deadline for submission?",
                        "What are the prerequisites for this course?",
                        "Please provide information about the company’s benefits.",
                        "When does the event start?",
                        "I’d like to know more about your services.",
                        "Can you send me the documentation?",
                        "What's included in the package?",
                        "Do you have any case studies I can read?",
                        "Who should I contact for support?",
                        "Can I get the specifications for the new product?",
                        "Please tell me more about the refund policy.",
                        "What is the expected delivery time?",
                        "Can you clarify the payment terms?",
                        "Where can I find the project files?",
                        "I need the full itinerary for the trip.",
                        "How does the subscription model work?",
                        "What’s the pricing breakdown?",
                        "Can you give more insight into your approach?",
                        "Could you explain the next steps?",
                        "I’m looking for the schedule of sessions.",
                        "Who’s the point of contact for this project?",
                        "What are the limitations of this tool?",
                        "Please let me know the requirements.",
                        "How do I access the dashboard?",
                        "What’s the process to request a demo?",
                        "Could you send me the slide deck?",
                        "Can I get the timeline for this initiative?",
                        "What’s the expected output from our end?",
                        "I’d like to request further details.",
                        "Can I receive the login credentials?",
                        "Where is the training material stored?",
                        "What format should the report be in?",
                        "Can you describe the role responsibilities?",
                        "When will the next update be available?",
                        "Please send over the list of deliverables.",
                        "What’s the average response time for support?",
                        "How do I enroll in the program?",
                        "Can you confirm the address for the event?",
                        "I need help understanding the usage metrics.",
                        "Please explain the account setup process.",
                        "Can you give a breakdown of your fees?",
                        "What documents do I need to bring?",
                        "Where can I submit my application?",
                        "Do you have a sample report?",
                        "Can I get access to the beta version?",
                        "Please confirm if this is the right procedure.",
                        "What’s the difference between the plans?",
                        "How should we prepare for the kickoff meeting?",
                        "Can you provide more details about the event mentioned?",
                        "I need additional information regarding the policy update.",
                        "What does this term in the contract mean?",
                        "Could you share more about the requirements listed?",
                        "Please send me the documentation for this process.",
                        "I'm looking for details about the training session.",
                        "Can I get the specs for the new product?",
                        "Where can I find more information about this topic?",
                        "Who should I contact for further clarification?",
                        "Can you tell me when this feature will be available?",
                        "Please share the official guidelines.",
                        "Could you explain how this workflow operates?",
                        "I’d like to understand the next steps.",
                        "Can you break this down for me?",
                        "What does the budget include?",
                        "I need to know more about your services.",
                        "Where can I read about the project scope?",
                        "Kindly send me the pricing breakdown.",
                        "Can I have a list of deliverables?",
                        "Could you clarify what’s required on our end?",
                        "Do we have any documentation on this tool?",
                        "Please explain what this abbreviation stands for.",
                        "What’s the expected timeline for this task?",
                        "How does this new policy impact us?",
                        "Can I get more context on the attached report?",
                        "I need further insights into this issue.",
                        "Can you elaborate on the changes made?",
                        "What resources do I need to get started?",
                        "Could you walk me through the process?",
                        "Are there any FAQs I can refer to?",
                        "Where is the link to the signup page?",
                        "Please provide the checklist.",
                        "Can I access the previous reports?",
                        "What’s the logic behind this update?",
                        "Could you send over the latest figures?",
                        "What are the expected deliverables from our side?",
                        "How will this affect our department?",
                        "Is there a file attached with more info?",
                        "Please explain the reasoning for this change.",
                        "Are there any examples you can share?",
                        "What does this alert signify?",
                        "Can someone clarify the email I received earlier?",
                        "Do we have a guide on this?",
                        "What’s included in the new onboarding process?",
                        "Can I request the full dataset?",
                        "Kindly forward the webinar details.",
                        "Could you provide the slide deck?",
                        "I need clarification on the KPIs mentioned.",
                        "Is there any documentation on this feature?",
                        "What are the prerequisites for this course?"],

    "WebSearch" : ["Find recent articles about AI in healthcare.",
                    "Search for the latest Python tutorials.",
                    "Can you look up the weather forecast for tomorrow?",
                    "Find me news about the Apple product launch.",
                    "Search for top restaurants near me.",
                    "Look up the definition of 'neural networks'.",
                    "Find reviews for the new Tesla model.",
                    "Search for remote internships in data science.",
                    "Look up recent studies on climate change.",
                    "Search for job openings at Google.",
                    "Find trending research in quantum computing.",
                    "Search for the best budget laptops under 50000.",
                    "Find tips to improve email productivity.",
                    "Search how to integrate Slack with Google Calendar.",
                    "Look up tutorials on FastAPI.",
                    "Search for upcoming tech conferences in India.",
                    "Find the latest stock price of Microsoft.",
                    "Search for healthy meal prep recipes.",
                    "Look up TensorFlow vs PyTorch comparison.",
                    "Search how to create a portfolio website.",
                    "Find a beginner guide to machine learning.",
                    "Search for freelance platforms for developers.",
                    "Look up symptoms of vitamin D deficiency.",
                    "Search best books to learn deep learning.",
                    "Find trending topics on Twitter.",
                    "Look up cheapest flights to Delhi this weekend.",
                    "Search for top-rated productivity apps.",
                    "Find online courses on MLOps.",
                    "Search for YouTube videos about ResNet architecture.",
                    "Look up historical data on Bitcoin.",
                    "Find the schedule for the Indian Premier League.",
                    "Search for the latest Android update release.",
                    "Look up best practices for writing research papers.",
                    "Find open-source datasets for NLP.",
                    "Search for startups working in generative AI.",
                    "Look up public holidays in 2025.",
                    "Search for benefits of meditation.",
                    "Find study material for GATE CSE.",
                    "Search how to convert a TensorFlow model to ONNX.",
                    "Find resume tips for freshers.",
                    "Search for cafes with Wi-Fi near my location.",
                    "Look up the movie reviews for 'Oppenheimer'.",
                    "Find trending Kaggle competitions.",
                    "Search for scholarships for Indian students abroad.",
                    "Look up email etiquette tips for professionals.",
                    "Search for guides on using GitHub Actions.",
                    "Find discounts on online learning platforms.",
                    "Search for volunteer opportunities in Delhi.",
                    "Look up how to optimize BERT models.",
                    "Find recent news about space exploration.",
                    "Can you look this up online for me?",
                    "Find recent news about the Mars mission.",
                    "Search the web for the latest AI trends.",
                    "Get me articles about climate change effects.",
                    "Look up the symptoms of vitamin D deficiency.",
                    "Find tutorials on building a REST API.",
                    "Can you check what time the movie starts?",
                    "Search for nearby Italian restaurants.",
                    "Get the weather forecast for tomorrow in Delhi.",
                    "Look up the best laptops under 50k.",
                    "Search for scholarship opportunities for CS students.",
                    "Find a good blog on productivity tips.",
                    "Look into current stock prices of Tesla.",
                    "Search for books similar to 'Atomic Habits'.",
                    "Find research papers on neural networks.",
                    "Search for an alternative to Google Docs.",
                    "Can you get the latest cricket match score?",
                    "Look up travel restrictions for Canada.",
                    "Search for universities offering ML courses.",
                    "Find info on how to file taxes online.",
                    "Search for recipes using only eggs and cheese.",
                    "Get an online Python compiler.",
                    "Look up how to clean laptop fans safely.",
                    "Find a comparison between GPT-4 and Claude.",
                    "Can you search for freelance writing gigs?",
                    "Find the latest tech jobs in Bangalore.",
                    "Search for recent advancements in robotics.",
                    "Get a list of the top 10 sci-fi movies.",
                    "Find details about the budget 2025.",
                    "Search for vegan protein powder reviews.",
                    "Look for open-source project ideas.",
                    "Search for famous quotes by Einstein.",
                    "Find a tool to convert PDF to Word.",
                    "Can you look up YouTube channel analytics tools?",
                    "Search how to improve sleep quality.",
                    "Look for current COVID-19 guidelines.",
                    "Search how to apply for a driving license online.",
                    "Find popular tourist attractions in Manali.",
                    "Search for methods to boost concentration.",
                    "Look up GitHub trending repos today.",
                    "Find online certification courses in cloud computing.",
                    "Search for easy dessert recipes.",
                    "Can you check what’s trending on Twitter?",
                    "Look up latest breakthroughs in cancer research.",
                    "Search how to write a cover letter for freshers.",
                    "Get me the best mobile phone deals today.",
                    "Look up upcoming hackathons this month.",
                    "Search for productivity extensions for Chrome.",
                    "Find examples of professional portfolio websites."],

    "SlackForward" : [  "Can you send this email to our Slack channel?",
                        "Please forward this message to the #general channel on Slack.",
                        "Share this email with the product team on Slack.",
                        "Put this on Slack so everyone can see.",
                        "Send this conversation to Slack immediately.",
                        "Push this email into our marketing Slack group.",
                        "Please share this with the Slack engineering group.",
                        "Can you notify the team on Slack with this email?",
                        "Forward the contents of this email to Slack.",
                        "Copy this over to Slack for reference.",
                        "Send this message to our project Slack workspace.",
                        "Post this email on the Slack updates channel.",
                        "Push this to the Slack thread we discussed yesterday.",
                        "Drop this into Slack for quick visibility.",
                        "Can you put this message in our Slack channel?",
                        "Send this over Slack so the design team sees it.",
                        "Please share this email in Slack.",
                        "Post this email to our shared Slack space.",
                        "Put this thread in the Slack team chat.",
                        "Share this with #announcements in Slack.",
                        "Push this into Slack right away.",
                        "Can you copy this email to our Slack discussion?",
                        "Forward this email to Slack for everyone to view.",
                        "Put this on Slack so the rest of the team can react.",
                        "Paste this email in Slack.",
                        "Can you notify everyone by posting this to Slack?",
                        "Send this message to Slack with a quick note.",
                        "Add this email content to Slack please.",
                        "Let’s put this message in the Slack thread.",
                        "Drop this in Slack for team discussion.",
                        "Send this update to Slack, ASAP.",
                        "Share this on Slack under the #urgent channel.",
                        "Forward this to Slack and tag the leads.",
                        "Upload this email to Slack.",
                        "Slack this to the appropriate group.",
                        "Push this to Slack and notify the dev team.",
                        "Share this message in the team’s Slack workspace.",
                        "Include this in the Slack daily updates channel.",
                        "Send this on Slack where we track client feedback.",
                        "Can you forward this to Slack and mention Sarah?",
                        "Broadcast this over Slack.",
                        "Post this thread to Slack and get feedback.",
                        "Ping Slack with this message for quick replies.",
                        "Publish this in Slack for internal visibility.",
                        "Send this email straight to Slack.",
                        "Add this to Slack for easy access.",
                        "Please post this email into Slack for archiving.",
                        "Transfer this message to our Slack logs.",
                        "Let’s Slack this message to everyone.",
                        "Please deliver this content to Slack.",
                        "Please forward this message to the team on Slack.",
                        "Send this update to the #general channel.",
                        "Share these meeting notes on Slack.",
                        "Push this reminder to the Slack group.",
                        "Send this to the devs via Slack.",
                        "Can you post this summary on Slack?",
                        "Forward this to the marketing channel.",
                        "Drop this message in the #random channel.",
                        "Push this to Slack for the design team.",
                        "Send this status update to the client group.",
                        "Post this announcement on Slack.",
                        "Send the weekly report on Slack.",
                        "Can you notify the #ops team with this?",
                        "Share this email content on Slack.",
                        "Forward this deadline extension to the team.",
                        "Send a Slack message about this bug.",
                        "Push this feature update to Slack.",
                        "Drop this in the standup channel.",
                        "Please inform the QA team on Slack.",
                        "Relay this information to #project-x.",
                        "Post this event on the Slack calendar.",
                        "Send this user feedback to the support team Slack.",
                        "Notify everyone on Slack about the deployment.",
                        "Ping the team in Slack with this alert.",
                        "Send the revised document link to Slack.",
                        "Forward this budget approval to finance Slack.",
                        "Post this agenda in the planning channel.",
                        "Let the interns know via Slack.",
                        "Slack this announcement to all hands.",
                        "Send this template through Slack.",
                        "Forward this Zoom link to the meeting channel.",
                        "Drop the schedule on Slack.",
                        "Tell the team on Slack the deadline changed.",
                        "Post this bug list to the tech channel.",
                        "Send this to @john in Slack.",
                        "Slack this to whoever's on shift now.",
                        "Can you forward this proposal to Slack?",
                        "Share the hiring update with #hr.",
                        "Send the project summary to Slack now.",
                        "Update Slack with this issue.",
                        "Push this checklist to the onboarding group.",
                        "Let everyone in Slack know we’re live.",
                        "Post this policy update on Slack.",
                        "Share this invoice in the finance channel.",
                        "Update Slack with this lead’s info.",
                        "Ping the design team on Slack with this idea.",
                        "Share this GitHub link on Slack.",
                        "Notify @managers about this situation in Slack.",
                        "Send the report to Slack before 6PM.",
                        "Please post this article to #learning."],

    "SceduledEvent" : ["Can we set up a meeting to discuss the quarterly results?",
                        "Please schedule a meeting with the product team next week.",
                        "Let's arrange a call with the client tomorrow at 3 PM.",
                        "Add our weekly sync-up to the calendar.",
                        "Book a room for the Friday strategy meeting.",
                        "I’d like to organize a session for the roadmap review.",
                        "Please block some time on my calendar for the HR interview.",
                        "Let’s fix a time to go over the proposal.",
                        "Schedule a Zoom call for the design presentation.",
                        "Mark your calendar for a team briefing on Monday.",
                        "I want to set up a meeting with the stakeholders.",
                        "Add a meeting on Thursday to discuss campaign performance.",
                        "Could you please schedule our sprint planning session?",
                        "Set up a catch-up meeting with R&D team next Tuesday.",
                        "I want to arrange a demo session this Friday.",
                        "Put the tech review in the calendar for 2 PM.",
                        "Let's schedule a one-on-one this week.",
                        "Reserve time for a retrospective on Wednesday.",
                        "Please create a calendar event for the user feedback review.",
                        "I need a meeting on Friday to go through the updated deck.",
                        "Add a call with the marketing head to the calendar.",
                        "Can you fix a meeting slot for our partnership talk?",
                        "Schedule a recurring sync-up with the dev team.",
                        "Set a calendar invite for the new hire orientation.",
                        "Block 30 minutes for the financial review.",
                        "Arrange a call with the legal team regarding the NDA.",
                        "Let’s finalize a time for the roadmap discussion.",
                        "Please schedule the monthly progress review.",
                        "Add a calendar reminder for the upcoming product launch.",
                        "Plan a session on Monday for the budget discussion.",
                        "Fix a slot for our quarterly strategy review.",
                        "Can you schedule our client onboarding meeting?",
                        "Let's organize a team catch-up next Friday.",
                        "Set up a session to talk about OKRs.",
                        "Book a time with Alex to review the project timeline.",
                        "Add our training workshop to the calendar.",
                        "Create an event for the team lunch tomorrow.",
                        "I want to have a quick sync with the QA team.",
                        "Schedule a planning call with the vendors.",
                        "Add the conference call to everyone's calendar.",
                        "Block some time for the UI/UX feedback session.",
                        "Let’s plan our team offsite meeting.",
                        "Mark the review call for Thursday at 5 PM.",
                        "Arrange a weekly review meeting with sales.",
                        "Put our monthly standup in the calendar.",
                        "Set up a time to discuss the bug backlog.",
                        "Book an hour with design team for the prototype discussion.",
                        "Add a follow-up meeting for the support case.",
                        "Let's meet on Wednesday to align on priorities.",
                        "Please arrange the board meeting for next month.",
                        "Schedule the kickoff meeting for our new project.",
                        "Create a calendar invite for the demo walkthrough.",
                        "Put a discussion slot for investor feedback.",
                        "Schedule a meeting with the design team for next Wednesday at 2 PM.",
                        "Add a calendar event for the client call on Friday morning.",
                        "Set up a Zoom call with the HR team on Monday at 11 AM.",
                        "Book a meeting with the supplier regarding the new shipment.",
                        "Remind me about the budget review session next Thursday.",
                        "Create an event for the performance evaluation meeting.",
                        "Block time on my calendar for the marketing sync-up.",
                        "Plan a team stand-up for tomorrow morning.",
                        "Add a reminder for the legal consultation on the 10th.",
                        "Organize a catch-up with the interns on Friday.",
                        "Fix a call with the CEO next week.",
                        "Please put the team meeting on my schedule at 3 PM today.",
                        "Can you book a room for our brainstorming session at 5?",
                        "Set up a calendar entry for the code review with the developers.",
                        "Schedule a follow-up meeting with the stakeholders.",
                        "Add the product launch event to the calendar.",
                        "Arrange a one-on-one meeting with my manager.",
                        "Put the financial planning discussion on Friday's schedule.",
                        "Set a reminder for tomorrow's townhall at 4 PM.",
                        "Book a session to review the quarterly targets.",
                        "Block my calendar for a feedback meeting with the client.",
                        "Plan a catch-up call for project status updates.",
                        "Add a strategic planning meeting on next Monday.",
                        "Create an event for onboarding new employees.",
                        "Schedule a check-in with the project lead every Tuesday.",
                        "Organize a session to discuss the updated roadmap.",
                        "Set a Google Meet event for the UX review.",
                        "Arrange an interview with the data scientist candidate.",
                        "Schedule a meeting to finalize the hiring process.",
                        "Block time for a retrospective after the sprint ends.",
                        "Add the weekly sync call with the vendors.",
                        "Put the compliance audit meeting on my calendar.",
                        "Plan the OKR alignment session next week.",
                        "Set a call with the external consultant tomorrow.",
                        "Schedule a discussion on the customer feedback report.",
                        "Book a time for evaluating our Q2 goals.",
                        "Create a recurring meeting for every Friday team check-in.",
                        "Add a session for training the new joiners.",
                        "Fix a meeting to go over the invoice issues.",
                        "Schedule the collaboration session with the design and dev team.",
                        "Plan a roadmap review with leadership.",
                        "Put a calendar reminder for the merger announcement meeting.",
                        "Add an event for the new software onboarding demo.",
                        "Set up a planning meeting for the next sprint.",
                        "Create a calendar entry for reviewing this quarter's analytics.",
                        "Organize a workshop on effective communication skills.",
                        "Book a meeting room for the client presentation.",
                        "Add an event to discuss the website redesign plan.",
                        "Schedule the quarterly all-hands meeting.",
                        "Block a slot for a follow-up on the legal case.",
                        "Plan a knowledge transfer session with outgoing staff."],

    "AutomatedReply" : ["Thank you for reaching out. I’ll get back to you shortly.",
                        "I’ve received your message and will reply soon.",
                        "Appreciate your email. I’ll respond as soon as I can.",
                        "Thanks for the update. I’ll look into it.",
                        "Got it. I’ll get back to you with the details.",
                        "I’m currently away from my desk but will respond soon.",
                        "Thanks for letting me know. I’ll check and reply.",
                        "I’ll review the document and share my thoughts shortly.",
                        "Noted, I’ll follow up on this.",
                        "Thanks for your patience. I’ll respond soon.",
                        "I’ve seen your email. Will reply after my meeting.",
                        "I’m on it and will update you soon.",
                        "Thanks for the heads-up. I’ll look into it today.",
                        "Appreciate the reminder. I’ll handle it.",
                        "I’ll get back to you once I review this.",
                        "Noted. Will take care of it.",
                        "Thanks. I’ll get back with a response shortly.",
                        "Your email has been received. I’ll get back to you.",
                        "Will respond with more info soon.",
                        "I’ve noted your message. Will reply after reviewing.",
                        "Thanks for reaching out. I’ll respond after checking.",
                        "Understood. I’ll take a look and reply.",
                        "Got your email. I’ll share my thoughts soon.",
                        "Thanks, I’ll provide feedback shortly.",
                        "Received. I’ll follow up soon.",
                        "I’ll reply after confirming the details.",
                        "Appreciate the message. Will revert shortly.",
                        "I’m reviewing this and will respond soon.",
                        "I’ll revert once I check the calendar.",
                        "Noted, thanks. I’ll respond shortly.",
                        "Got it. Let me look into it and reply.",
                        "I’m working on it and will respond soon.",
                        "I’ll be in touch shortly with my response.",
                        "Thanks, I’ll update you by EOD.",
                        "Received and acknowledged. Will respond.",
                        "I’ll share an update once it’s done.",
                        "Will do. I’ll confirm in a bit.",
                        "Let me get back to you on this.",
                        "I’ll respond after discussing with the team.",
                        "I’ll check with the manager and get back.",
                        "Got your query. I’ll reply once I have the answer.",
                        "I’ll respond after some clarification.",
                        "Thanks, I’ll circle back with details.",
                        "Message received. Will follow up shortly.",
                        "I’ve taken note. Expect my response soon.",
                        "Thanks. Let me confirm and reply.",
                        "Will revert to you after analyzing.",
                        "Thanks, I’ll get back after reviewing.",
                        "I’m reviewing it and will respond ASAP.",
                        "I’ve received the request. Will follow up soon.",
                        "I’ll address this and reply soon.",
                        "Thank you for your email. I will get back to you shortly.",
                        "I appreciate your message. I’ll respond soon.",
                        "Received your email. I will review it and reply shortly.",
                        "Thanks for reaching out. I'll follow up soon.",
                        "I’ve got your email and will respond as soon as I can.",
                        "Thank you for the information. I’ll get back to you.",
                        "Your message has been received. I’ll reply shortly.",
                        "I appreciate your email. Expect a response soon.",
                        "Thanks! I’ll take a look and reply soon.",
                        "I’ll respond to your query shortly. Thank you.",
                        "Thanks for the update. I’ll review it and reply.",
                        "Got your message. I’ll check and get back to you.",
                        "I’m currently reviewing your request. Will reply soon.",
                        "Thanks for the details. I’ll respond after reviewing.",
                        "Thanks! I’ll respond after going through the email.",
                        "I’m currently busy but will reply shortly.",
                        "Received your email. Will respond once I have more info.",
                        "Thanks for contacting me. I’ll get back to you soon.",
                        "I appreciate your patience. I’ll reply shortly.",
                        "Got it! I’ll respond with more info soon.",
                        "Thank you for your patience. I’ll reply soon.",
                        "I will get back to you after checking with the team.",
                        "Thanks for the heads up. Replying soon.",
                        "Thanks. Let me look into it and I’ll reply.",
                        "I’ve noted your message. I’ll respond soon.",
                        "Thanks for the quick update. I’ll follow up shortly.",
                        "I’ve seen your request. I’ll reply after reviewing it.",
                        "Appreciate the info. I’ll get back to you soon.",
                        "Thanks for the clarification. Replying soon.",
                        "Understood. I’ll respond once I confirm a few things.",
                        "Got your point. I’ll respond after verifying.",
                        "Your message is being reviewed. I’ll reply shortly.",
                        "Thanks. I’ll check and let you know soon.",
                        "I’ll respond soon after going through the attachments.",
                        "Thanks for reaching out. Please expect a reply soon.",
                        "I’m on it. I’ll send you a reply shortly.",
                        "Thank you for your patience. Working on a reply.",
                        "Got your email. Crafting a response now.",
                        "I will reply to this as soon as I finish my current task.",
                        "Thanks. I’ll respond once I verify with the client.",
                        "Your message has been acknowledged. Replying soon.",
                        "I’m working on it. Will respond soon.",
                        "I will get back to you after checking my schedule.",
                        "Thanks. I’ll get back after discussing internally.",
                        "I appreciate your follow-up. Replying soon.",
                        "I’ll send a detailed response shortly. Thanks.",
                        "I’m looking into this. Expect a reply soon.",
                        "Reviewing your request. Will respond soon.",
                        "I’ve read your email. I’ll reply when I’m free.",
                        "Thanks. I’ll reply once I confirm the next steps.",
                        "I’m on the move right now, will reply soon."],
    
    "Others" : ["Hope you're doing well!",
                "Just checking in to see how things are going.",
                "Let me know if you need anything from my side.",
                "Have a great weekend!",
                "Please disregard my previous message.",
                "Following up on our earlier chat.",
                "This email is just to say hello!",
                "Wishing you the best in your new role!",
                "Thanks for the quick chat earlier.",
                "Let's catch up sometime soon.",
                "I'll be offline for the rest of the day.",
                "Just wanted to share a quick update.",
                "Sending you best wishes.",
                "Let me know your thoughts when you can.",
                "Looking forward to hearing from you.",
                "No action needed, just keeping you informed.",
                "Take your time, no rush.",
                "Thanks again for everything!",
                "I appreciate your continued support.",
                "This is just an FYI email.",
                "Feel free to ignore this if it's not relevant.",
                "Sharing this in case it's useful.",
                "Congratulations on your achievement!",
                "Happy to connect anytime.",
                "Hope everything is going great on your end.",
                "Talk to you soon!",
                "Let me know when you're free for a quick chat.",
                "Just realized I made a typo in my last email.",
                "Enjoy your vacation!",
                "Thanks for looping me in.",
                "Appreciate your attention on this.",
                "Happy Friday!",
                "Hope your week is going well.",
                "Just wanted to say thank you.",
                "Sending positive vibes your way.",
                "Have a relaxing day ahead.",
                "Thanks for being awesome!",
                "Feel free to reach out anytime.",
                "Hope this brightens your day.",
                "Have a safe trip!",
                "I'm here if you need anything.",
                "Nice speaking with you earlier.",
                "Let’s grab a coffee sometime.",
                "Thanks for taking the time to meet.",
                "Sending over a quick hello!",
                "Looking forward to our continued collaboration.",
                "Have a productive week ahead.",
                "It was great seeing you at the event.",
                "Stay safe and take care!",
                "Cheers!",
                "Just touching base.",
                "Hope you're having a great day!",
                "Just checking in to say hello.",
                "This is a test email. Please ignore.",
                "Here's a fun fact I thought you'd enjoy.",
                "Let’s catch up sometime soon!",
                "I found this meme hilarious, sharing it with you.",
                "Can you believe it's already April?",
                "How was your weekend?",
                "Sending birthday wishes your way!",
                "Just saying hi, no action needed.",
                "Hope everything's going well on your side.",
                "Long time no see—let's reconnect soon.",
                "This is just a friendly reminder to smile today!",
                "Remember that trip we talked about? Let’s plan it soon.",
                "I saw this quote and thought of you.",
                "Hope the weather is better on your side.",
                "Just sharing a random thought from today.",
                "Let me know if you’re free to chat sometime.",
                "Take care and stay safe!",
                "This email doesn’t require a reply.",
                "Hope your work is going smoothly.",
                "Just felt like dropping a quick note.",
                "Thinking of you, no need to respond.",
                "Sending you good vibes for the week ahead.",
                "You're doing great—keep it up!",
                "This made me smile, hope it does for you too.",
                "Let’s hang out soon!",
                "Just passing along good wishes.",
                "Nothing urgent, just checking in.",
                "I hope this message finds you well.",
                "Wishing you a productive week ahead.",
                "Sending you a virtual high-five!",
                "I hope you're taking time to relax.",
                "This is unrelated to work—just for fun!",
                "Hope you’re enjoying your day so far.",
                "This is just me being random.",
                "Don’t forget to take breaks!",
                "Take a moment to breathe today.",
                "Sometimes, no reason is the best reason to say hi!",
                "Hope you're drinking enough water today.",
                "Let’s take a break and chat soon.",
                "Stay awesome!",
                "Remember to stay positive.",
                "You're appreciated more than you know.",
                "I’m grateful for our friendship.",
                "Here’s something to brighten your day.",
                "Let’s catch up over coffee soon.",
                "I admire your work ethic.",
                "Take it easy and enjoy your day.",
                "Have a peaceful evening."]
}


rows = [(text, label) for label, samples in data.items() for text in samples]

df = pd.DataFrame(rows, columns=["text", "label"])
# csv_path = "intent_classifier/training_data/intent_samples.csv"
base_dir = os.path.dirname(__file__)
csv_path =  os.path.join(base_dir, "intent_data.csv")
df.to_csv(csv_path, index=False)